version: '3.8'

services:
  # ==========================================
  # 1. ИНФРАСТРУКТУРА (БД, Кэш, Брокер, S3, Метрики)
  # ==========================================
  postgres:
    image: postgres:15-alpine
    container_name: cobooking-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cobooking
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cobooking-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cobooking-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: cobooking-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: cobooking-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: cobooking-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped

  # ==========================================
  # 2. НАШИ GO МИКРОСЕРВИСЫ
  # ==========================================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080" # Открываем наружу только Gateway!
    environment:
      PORT: "8080"
      REDIS_ADDR: "redis:6379"
      JWT_SECRET: "MY_SUPER_SECRET_KEY_123"
      MS_AUTH_URL: "http://ms-auth:8081"
    depends_on:
      - redis
      - ms-auth
      - ms-places
      - ms-booking
      - ms-payments

  ms-auth:
    build: ./ms-auth
    container_name: ms-auth
    environment:
      PORT: "8081"
      POSTGRES_URL: "postgres://admin:password@postgres:5432/cobooking?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      JWT_SECRET: "MY_SUPER_SECRET_KEY_123"
    depends_on:
      - postgres
      - redis

  ms-places:
    build: ./ms-places
    container_name: ms-places
    environment:
      PORT: "8082"
      POSTGRES_URL: "postgres://admin:password@postgres:5432/cobooking?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_USER: "admin"
      MINIO_PASSWORD: "password123"
      MINIO_BUCKET: "workspaces"
    depends_on:
      - postgres
      - redis
      - minio

  ms-booking:
    build: ./ms-booking
    container_name: ms-booking
    environment:
      PORT: "8083"
      POSTGRES_URL: "postgres://admin:password@postgres:5432/cobooking?sslmode=disable"
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672/"
    depends_on:
      - postgres
      - rabbitmq

  ms-notifications:
    build: ./ms-notifications
    container_name: ms-notifications
    environment:
      PORT: "8084"
      POSTGRES_URL: "postgres://admin:password@postgres:5432/cobooking?sslmode=disable"
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672/"
    depends_on:
      - postgres
      - rabbitmq

  ms-payments:
    build: ./ms-payments
    container_name: ms-payments
    environment:
      PORT: "8085"
      POSTGRES_URL: "postgres://admin:password@postgres:5432/cobooking?sslmode=disable"
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672/"
    depends_on:
      - postgres
      - rabbitmq
