global:
  scrape_interval: 5s # Как часто собирать метрики

scrape_configs:
  - job_name: 'cobooking-services'
    static_configs:
      # host.docker.internal позволяет контейнеру достучаться до localhost твоего Arch Linux, где крутятся go run
      - targets: 
        - 'api-gateway:8080' # API Gateway
        - 'ms-auth:8081' # MS Auth
        - 'ms-places:8082' # MS Places
        - 'ms-booking:8083' # MS Booking
        - 'ms-notifications:8084' # MS Notifications
        - 'ms-payments:8085' # MS Payments
